$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf
# Sanguine Theme - Inspired by dark maroon and gold

$GTK_THEME = adw-gtk3-dark
$ICON_THEME = Papirus-Dark
$COLOR_SCHEME = prefer-dark

# Optional: The varibles above will be set automatically when the theme is loaded
# This exec commands will soon be deprecated

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(a52a2aff) rgba(d4a753ff) 45deg
    col.inactive_border = rgba(8b0000cc) rgba(4b0000cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(a52a2aff) rgba(d4a753ff) 45deg
    col.border_inactive = rgba(8b0000cc) rgba(4b0000cc) 45deg
    col.border_locked_active = rgba(a52a2aff) rgba(d4a753ff) 45deg
    col.border_locked_inactive = rgba(8b0000cc) rgba(4b0000cc) 45deg
}

decoration {
    rounding = 10
    shadow:enabled = false

    blur {
        enabled = true
        size = 5
        passes = 4
        optimizations = true
        ignore_opacity = true
        xray = false
    }
}

layerrule = unset,waybar
